version: '3.3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=sqs,s3
  worker:
    depends_on:
       - localstack
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "3000:3000" 
